name: "Hello World JS Action"
description: "A simple JavaScript GitHub Action that greets Hanaan"
name: "Hello World JS Action"
description: "A simple JS action example"
author: "Hanaan"


runs:
  using: "node16"
  main: "index.js"

inputs:
  name:
    description: "Name to greet"
    required: false
    default: "Hanaan"

outputs:
  greeting:
    description: "The greeting message"