name: "Hello World Js Action"
description: "A simple JavaScript action that prints 'Hello World' to the console."
author: "Hanaan"
runs:
  using: "node16"
  main: "index.js"

inputs:
name:
  description: "The name to greet"
  required: false
  default: "World"

Outputs:
greeting:
  description: "The greeting message"
  